# Server Configuration
server:
  port: 8686

# Eureka Configuration
eureka:
  instance:
    hostname: ${reportportal.eureka.instance.hostname:localhost}
    metadata-map:
      extension: tfs

  client:
    serviceUrl:
      defaultZone: http://${reportportal.eureka.hostname:localhost}:8761/eureka/

# MongoDB configuration
rp:
  mongo:
    host: ${reportportal.mongo.host:docker.local}
    port: 27017
    dbName: reportportal
#        user: user
#        password: 1q2w3e
    connectionsPerHost: 1000
    threadsAllowedToBlockForConnectionMultiplier: 1000
    connectTimeout: 20000
    socketTimeout: 60000
    maxWaitTime: 120000
    autoConnectRetry: true
    socketKeepAlive: true
    slaveOk: true
    writeTimeout: 0
    writeNumber: 1
    writeFsync: false
  cache:
      project:
        size: 1000
        expiration: 1
        info: 10
      ticket:
        size: 10000
        expiration: 5
      user:
        size: 1000
        expiration: 60

## Consul as service registry
spring:
  profiles: consul
  cloud:
    consul:
      enabled: true
      discovery:
        register: true
eureka:
  client:
    register-with-eureka: false
    enabled: false

## Eureka as service registry
spring:
  profiles: eureka
  cloud:
    consul:
      enabled: false
      discovery:
        register: false
eureka:
  client:
    register-with-eureka: true
    enabled: true